Update Testing Add update checker and bug fixes

diff --git a/.github/workflows/maven-build.yml b/.github/workflows/maven-build.yml
--- a/.github/workflows/maven-build.yml
+++ b/.github/workflows/maven-build.yml
@@ -45,7 +45,6 @@ jobs:
     if: >
       ${{ github.event_name == 'push' &&
       startsWith(github.event.head_commit.message, 'Update v') &&
-      github.event.head_commit.message matches '^Update v[0-9]+\\.[0-9]+(\\.[0-9]+)?$' &&
       !contains(github.event.head_commit.message, '-ignore') }}
     needs: build
     runs-on: ubuntu-latest
@@ -53,6 +52,15 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
+
+      - name: Validate Commit Message
+        run: |
+          echo "Validating commit message..."
+          if [[ ! "${{ github.event.head_commit.message }}" =~ ^Update\ v[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
+            echo "Invalid commit message format. Expected 'Update vX.X.X'."
+            exit 1
+          fi
+          echo "Commit message validated."
 
       - name: Upload to Modrinth
         run: |
